// Queries
export enum TasksQueryConstants {
  GET_TASKS = "GET_TASKS",
  GET_INFINITE_TASKS = "GET_INFINITE_TASKS",
  GET_TASK = "GET_TASK",
  GET_TASK_STATUS = "GET_TASK_STATUS",
}

// Mutations
export enum TasksMutationConstants {
  CREATE_TASK = "CREATE_TASK",
  UPDATE_TASK = "UPDATE_TASK",
  UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS",
  DELETE_TASK = "DELETE_TASK",
}
